# Generated by Django 6.0.7 on 2026-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='grupo_parcelamento',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcela_atual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='total_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
