# Generated by Django 6.0.7 on 2026-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_despesa_grupo_parcelamento_despesa_parcela_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
